### ISSUE TITLE
performance regression with v6

### ISSUE THREAD

**Issue by mbiebl** [PHPSocialNetwork/phpfastcache#463] opened 2017-05-21 12:00 UTC
### Configuration:

PhpFastCache version: 6.0.1 / 5.0.16
PHP version: 7.0
Operating system: Linux / Windows

#### Issue description:

I've updated a project to phpfastcache v6 and noticed a perfomance regression.
The project is running on windows using the wincache driver with php 7.0. The perfomance regression compared to 5.0.16 is between 15%-25%.

I've created a test case, which I've ran under Linux as well using the files backend. The numbers are comparable.
v5.0.16:
first run with empty cache: 14.666780948639
second run with full cache: 0.75569796562195

v6.0.1:
first run with empty cache: 17.629030942917
second run with full cache: 1.1219041347504

The code I used writes 100.000 entries and then reads them again from the cache:
```
<?php

require_once('vendor/autoload.php');

use \phpFastCache\CacheManager;

$cache = CacheManager::getInstance('files');
$cycles = 100000;

function compute_str($arg) {
    $str = __FUNCTION__ . '-' . $arg . '-' . 'michael@test.example.com';
    $key = str_replace(array('{', '}', '(', ')', '/', '\\', '@', ':'), '_', $str);
    return $key;
}

function compute_md5($arg) {
    $str = __FUNCTION__ . '-' . $arg . '-' . 'michael@test.example.com';
    $key = md5($str);
    return $key;
}

function compute_sha1($arg) {
    $str = __FUNCTION__ . '-' . $arg . '-' . 'michael@test.example.com';
    $key = sha1($str);
    return $key;
}


function compute($arg) {
    return compute_sha1($arg);
}

$before = microtime(true);
for ($i=0; $i<$cycles; $i++) {
    $key = compute($i);
    $cachedNum = $cache->getItem($key);
    if (is_null($cachedNum->get())) {
        $cachedNum->set($i*$i);
        $cache->save($cachedNum);
    } else {
        $num = $cachedNum->get();
        if ($num != $i*$i) {
            print ("Something went wrong: " . $i . " -> " . $num);
        }
    }
}
$after = microtime(true);
$duration = $after - $before;
print ('first run with empty cache: ' . $duration . "\n");

$before = microtime(true);
for ($i=0; $i<$cycles; $i++) {
    $key = compute($i);
    $cachedNum = $cache->getItem($key);
    if (is_null($cachedNum->get())) {
        $cachedNum->set($i*$i);
        $cache->save($cachedNum);
    } else {
        $num = $cachedNum->get();
        if ($num != $i*$i) {
            print ("Something went wrong: " . $i . " -> " . $num);
        }
    }
}
$after = microtime(true );
$duration = $after - $before;
print ('second run with full cache: ' . $duration . "\n");

$cache->clear();
```

**Comment by Geolim4** [comment] 2017-05-21 12:26
Hell thanks for that report,

I'll check it carefully.

Cheers,
Georges.

**Comment by Geolim4** [comment] 2017-05-21 13:27
Hello,

It seem that the performances are better when making use of saveDeferred then commit().

Can you try this in your use case ?

Thanks you very much,
Georges

**Comment by Geolim4** [comment] 2017-05-21 13:40
I may have been identified the culprit:
https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/Core/Pool/CacheItemPoolTrait.php#L66

Can you comment out these 3 lines and try again ?

**Comment by mbiebl** [comment] 2017-05-21 14:15
I've commented out lines 66-69. The results are basically the same, i.e. no noticable improvement.

**Comment by mbiebl** [comment] 2017-05-21 14:19
> It seem that the performances are better when making use of saveDeferred then commit().
> 
> Can you try this in your use case ?

Unfortunately I can't make use of safeDeferred() as in my "real" code, I don't actually run a loop, but I have many individual http requests.
The code I posted in https://github.com/PHPSocialNetwork/phpfastcache/issues/463#issue-230215975 is simply to illustrate the problem.

**Comment by Geolim4** [comment] 2017-05-21 14:36
Crap, I'm afraid that the new eventManager can be the source of the problem.
Try by adding a simple `return;` statement before the $eventName re-assignation here:

https://github.com/PHPSocialNetwork/phpfastcache/blob/final/src/phpFastCache/EventManager.php#L72

I'm currently not on my main environment development, so I can't make deeper tests, sorry :(

Thanks you,
Georges

**Comment by mbiebl** [comment] 2017-05-21 14:41
> Try by adding a simple return; statement before the $eventName re-assignation here:

Doesn't make a difference either.

**Comment by Geolim4** [comment] 2017-05-21 14:45
Last request, can you give me distinct numbers between getItem() and save() ?

I need to know if there's only one method or both that can be problematic.

Tomorrow I should get back my main env development.

Cheers,
Georges

**Comment by mbiebl** [comment] 2017-05-21 14:54
can you be a bit more specific which info you need?
As you can see above, I already have two loops, one with an empty cache which calls save, the second with a full cache, which doesn't need to call save.
There is a performance regression in both cases

**Comment by Geolim4** [comment] 2017-05-21 15:00
Yeah, in those both write operation loops, I would like to get the individual time took by getItem and save().

**Comment by mbiebl** [comment] 2017-05-21 15:24
Another interesting observation: If I remove ```$cache->clear();``` i.e. keep the cache on disk, a subsequent run with 5.0.16 takes 10s (vs 15s after nuking the cache).
With 6.0.1 it takes 17s even if there is already a cache on disk.

**Comment by Geolim4** [comment] 2017-05-21 15:29
Cache clear performance regression on files is related to this:
https://github.com/PHPSocialNetwork/phpfastcache/pull/432

Unfortunately I can't do anything against this specific regression.

However I'll take a look for the other regression, there's must be something global IMO.

Cheers,
Georges

**Comment by Geolim4** [comment] 2017-06-06 17:12
Do you noticed the same performance regression with key/value drivers-based ? (Redis, Memcache, Ssdb, etc).

**Comment by mbiebl** [comment] 2017-06-06 19:36
@Geolim4 I'm currently not using other backends aside from wincache and files, so I can't tell if there's a regression.

**Comment by Geolim4** [comment] 2017-06-06 20:41
Do you have noticed the same performance regression on Wincache ?

 

De : Michael Biebl [mailto:notifications@github.com] 
Envoyé : mardi 6 juin 2017 21:37
À : PHPSocialNetwork/phpfastcache <phpfastcache@noreply.github.com>
Cc : Georges.L <contact@geolim4.com>; Mention <mention@noreply.github.com>
Objet : Re: [PHPSocialNetwork/phpfastcache] performance regression with v6 (#463)

 

@Geolim4 <https://github.com/geolim4>  I'm currently not using other backends aside from wincache and files, so I can't tell if there's a regression.

**Comment by Geolim4** [comment] 2017-06-14 10:52
Bump :)

**Comment by mbiebl** [comment] 2017-06-14 18:02
Hi there! What kind of information are you missing from my side? If there is, can you help me get it for your?

**Comment by Geolim4** [comment] 2017-06-14 18:04
Hello :)

I would like that you test your huge dataset with another memory backend-based, such as Redis/Memcache/Ssdb. Can you ?

Cheers,
Georges

**Comment by mbiebl** [comment] 2017-06-14 18:10
I'm not using any other backends so far, i.e. I don't have redis or other backends installed. Is this crucial to debug the regressions in the files/wincache backend? I'm asking, because I'm not sure how much work it would be to setup said backends.

**Comment by Geolim4** [comment] 2017-06-14 18:15
Tests with memcached should be good.
I have to be sure that it's Files driver-related and not globally-related.

**Comment by mbiebl** [comment] 2017-06-15 09:26
I've been running the test on Linux (Debian Sid, with php7 and memcached 1.4.33). The performance regressions are in the same ballpark as with the files and wincache backend

v5.0.16
```
first run with empty cache: 13.802587032318
second run with full cache: 0.87336182594299
```
v6.0.1
```
first run with empty cache: 15.565384149551
second run with full cache: 1.3187818527222
```

**Comment by mbiebl** [comment] 2017-06-15 09:28
You can use the test script I attached to https://github.com/PHPSocialNetwork/phpfastcache/issues/463#issue-230215975 if you want to reproduce the results yourself

**Comment by Geolim4** [comment] 2017-06-22 16:43
I'm still digging to find out a way to get back close of the previous performance...
Not forgotten :)

**Comment by Geolim4** [comment] 2017-06-22 17:41
The funny thing is that on Redis the difference is pretty weak
![capture](https://user-images.githubusercontent.com/1332071/27447822-cf65d2b2-5782-11e7-9268-e3edb4f4e8bf.PNG)
 oO...

**Comment by Geolim4** [comment] 2017-06-22 19:58
I identified multiple points that are, cumulated, the source of the performances regression:

- Files Driver
  - https://github.com/PHPSocialNetwork/phpfastcache/pull/432 Like i said previously, unfortunately I can't do anything against this specific regression.
- Global: 
  - cfd763779ab549db47cda310180df45afffbe3c2 Due to the Psr6 specifications this regexp must be tested for each call to getItem(). However I'll move this one after `$this->itemInstances` check, because ots useless to test it each time even if the item instance already exists.
  - There was a micro-performance issue with EventManager: the onXxxxxx string concatenation
  - There was two micro-performance issue with getItem() method: The use of Reflection API was a bad idea when used in huge loop operations
  - There was a micro-performance issue with getEncodeKey: The item hash was computed on the fly for every method call and not temporary stored in a distinct property.
  - There was a micro-performance with the use of array_key_exists on huge loop operations, now replaced with isset()

HOWEVER...
The V6 introduced a some improvements. We can't expect at all to have the exact same benchmark as with the V5. But I do agree with you, there's a non-negligible performance difference between the V5 and V6.

I made a first commit that will fine-tune the code called in huge loop operations. I also plan to work on possible optimizations day after day.

**Comment by Geolim4** [comment] 2017-06-22 20:06
@mbiebl You can do some tests if you want (not released yet, use dev-master)

**Comment by Geolim4** [comment] 2017-06-25 11:50
@mbiebl Bump :)

**Comment by Geolim4** [comment] 2017-06-26 09:08
Hello,

Please check your minimum-stability in your composer.json :)

**Comment by mbiebl** [comment] 2017-06-27 01:37
I added ```"minimum-stability" : "dev"``` to my composer.json, but that didn't work. Apparently I'm doing something wrong. I see thought that you you have release 6.0.2, so I ran a test against that:
```
v5.0.16
first run with cold/empty cache: 15.171237945557, misses: 100000
second run with hot/full cache: 0.80318379402161, misses: 0
first run with cold/empty cache: 15.268904924393, misses: 100000
second run with hot/full cache: 0.82464909553528, misses: 0
first run with cold/empty cache: 15.326946020126, misses: 100000
second run with hot/full cache: 0.81104683876038, misses: 0

v6.0.1
first run with cold/empty cache: 17.714466094971, misses: 100000
second run with hot/full cache: 1.2769951820374, misses: 0
first run with cold/empty cache: 17.475311994553, misses: 100000
second run with hot/full cache: 1.1392340660095, misses: 0
first run with cold/empty cache: 18.510245084763, misses: 100000
second run with hot/full cache: 1.3172750473022, misses: 0

v6.0.2
first run with cold/empty cache: 16.973572015762, misses: 100000
second run with hot/full cache: 0.86043882369995, misses: 0
first run with cold/empty cache: 16.6197681427, misses: 100000
second run with hot/full cache: 0.84666991233826, misses: 0
first run with cold/empty cache: 16.184941053391, misses: 100000
second run with hot/full cache: 0.84634685516357, misses: 0
```

It's better, that not quite back to v5

**Comment by Geolim4** [comment] 2017-06-27 12:02
Like I said, especially for the files driver that now made an additional cleanup, there is no way to get better performance than the v5 with all improvement we made. I'm still looking for a solution, though there's nothing more that I can do immediately.

**Comment by mbiebl** [comment] 2017-06-27 19:49
Ok, got it. Thanks a lot for your support so far @Geolim4 !

**Comment by Geolim4** [comment] 2017-06-27 20:11
I added two additional commits that should improve a bit the performances. Nothing blatant, but that's something at least.

**Comment by Geolim4** [comment] 2017-07-15 01:13
I'm closing this one, improving the V6 performances will be one my first priority along this version lifetime.
Thanks for the accurate benchmark.

**Closed** 2017-07-15 01:13 UTC
Labels: 6.0, [-_-] In Process, ^_^ enhancement, ^_^ Fixed
