### ISSUE TITLE
setup redis?

### ISSUE THREAD

**Issue by reimax** [PHPSocialNetwork/phpfastcache#656] opened 2018-09-25 08:44 UTC
"phpfastcache/phpfastcache": "^7.0"
php 7.1
ubuntu 18.04

i try use phpfastcache witch redis. my config:
`
use Phpfastcache\CacheManager;
use Phpfastcache\Config\ConfigurationOption;

require_once '/vendor/phpfastcache/vendor/autoload.php';		
CacheManager::setDefaultConfig(new ConfigurationOption([
				'host' => '127.0.0.1',
				'port' => 6379,
				'database' => 15,
				'password' => '', 
			]));
$cache = CacheManager::getInstance('redis');
`

get error:

> Invalid option(s) for the config Phpfastcache\Config\ConfigurationOption: host, port, database, password

how fix this?

if i use files driver it is work.

**Comment by Geolim4** [comment] 2018-09-25 08:51
Hello,

Did you rood the migration guide ?
https://github.com/PHPSocialNetwork/phpfastcache/blob/master/docs/migration/MigratingFromV6ToV7.md#configuration-option-type


Mhhh 🤔 ....
Cheers,
Georges

**Comment by Geolim4** [comment] 2018-09-25 08:52
Duplicate of #612

**Closed by Geolim4** 2018-09-25 08:52 UTC
Labels: 7.0, :) Closed, :] Not a bug

**Comment by reimax** [comment] 2018-09-25 08:56
yes and files work, but redis not. there is a working example under redis?

**Comment by Geolim4** [comment] 2018-09-25 08:58
Like I said, read the doc carefully....
> For non-global option you MUST use the specific Config object provided for each drivers

```php
// The recommanded way is to use an alias to not confuse yourself 
use Phpfastcache\Drivers\Files\Config as FilesConfig;

$config = new FilesConfig();
$config->setPath('/an/absolute/path');
$config->setSecureFileManipulation(true);
$cacheInstace = CacheManager::getInstance('Files', $config);

// This also works well:
$cacheInstace = CacheManager::getInstance('Files', new FilesConfig([
  'path' => '/an/absolute/path']
));
```
Adapt the code for Redis...

**Comment by reimax** [comment] 2018-09-25 09:39
read and like I said: not work.
remove phpfastcache, use other. thanks for your help.

**Comment by reimax** [comment] 2018-09-26 13:08
i adapt example and use

> use Phpfastcache\Drivers\Redis\Config as RedisConfig

**Comment by Geolim4** [comment] 2018-09-26 13:13
Yes, the options your specified belong to the Redis Config, not the base config class :)

**Comment by reimax** [comment] 2018-10-03 05:43
Thanks, I noticed that. The problem was solved by installing an extension for php to work with redis
