### ISSUE TITLE
Fallback conf with Redis

### ISSUE THREAD

**Issue by aradhell** [PHPSocialNetwork/phpfastcache#586] opened 2018-03-11 20:37 UTC
### Configuration:

PhpFastCache version: 6+
PHP version: 5.6
Operating system: Centos 7

#### Issue description:

Hello,

  I am trying to configure FastCache with Redis and Fallback option but requests printing Exceptions instead of fallbacking to Files. So it doesn't fallback to Files if Redis server is not working or responding.  What is the proper solution for this situation ?

Thanks !

```
self::$cacheInstance = CacheManager::getInstance('redis',[
                    'host' => '31.xx',
                    'port' => 6379,
                    'password' => 'password',
                    'fallback'=>'Files',
                    'path'=>'./redisTemp'
                ]);
```

```
<br />
<b>Warning</b>:  Redis::connect(): connect() failed: Connection refused in <b>/home/xxx/public_html/mansion/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Redis/Driver.php</b> on line <b>133</b><br />
<br />
<b>Fatal error</b>:  Uncaught exception 'RedisException' with message 'Redis server went away' in /home/xx/public_html/mansion/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Redis/Driver.php:84
Stack trace:
#0 /home/xx/public_html/mansion/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Redis/Driver.php(84): Redis-&gt;get('1fortune_teller...')
#1 /home/xx/public_html/mansion/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/Pool/CacheItemPoolTrait.php(76): phpFastCache\Drivers\Redis\Driver-&gt;driverRead(Object(phpFastCache\Drivers\Redis\Item))
```

**Comment by Geolim4** [comment] 2018-03-11 22:22
Hello,

The "path" configuration is conflicted between Predis and Files:
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-The-driver-options#hostauthenticating-options-

In the v7 this behavior will probably change using a dedicated fallback configuration to avoid any configuration conflict.

Also the fallback option is only working if the DriverCheck() method has failed.
This option does not cover wrong configurations / back-end issues.

Cheers,
Georges.

**Comment by aradhell** [comment] 2018-03-11 22:26
@Geolim4 So are you going to add a fallback cover for cache server failures in v7 ?

**Comment by Geolim4** [comment] 2018-03-11 22:30
Not at all ! 

I only plan to add a subconfig for fallback drivers.
Server failure cannot be handled because there's too many kind of exception to catch for each driver and depending where the exception is thrown it's impossible to fallback immediately (E.g. CRUD operations).

If you have server failures it's up to you to catch the exception/fix the issue.

The fallback driver only catches "missing php extensions/dependencies".

**Comment by aradhell** [comment] 2018-03-11 22:51
So do you think it is a right approach to ping the server at first and change instance type ?

**Comment by Geolim4** [comment] 2018-03-11 23:05
It's up to you to do this ;)
The right approach is to ensuring yourself that the Redis server stays up !

I'm closing this one since this is not a bug.

Cheers,
Georges.

**Closed by Geolim4** 2018-03-11 23:05 UTC
Labels: 6.1, 7.0, :] Not a bug

**Comment by Geolim4** [comment] 2018-03-12 00:14
I just added dedicated fallback configuration for the V7:

https://github.com/PHPSocialNetwork/phpfastcache/commit/501a7e6094f4dc0c5c4cd2d41c35f4bbf214a895

**Comment by remowashere** [comment] 2018-08-14 13:49
I had the same issues and fixed it by adding a ping() before loading the Redis driver;

`CacheManager::setDefaultConfig(new ConfigurationOption(['path' => __DIR__.'/cache']));
$cache = CacheManager::getInstance('Files');

// Check if we support Redis AND if the server is running

if (class_exists('Redis')){
    $redis = new Redis();
    try {
        $redis->connect('3x.xxx.xxx.7', 6379);
        if ($redis->ping()){
            $cache = CacheManager::getInstance('redis', new Config([
                'host' => '3x.xxx.xxx.7',
                'port' => 6379,
                'fallback' => 'Files'
            ]));
        }
    }catch (Exception $e) {
        // Just use the Files driver instead
        // print_r($e->getMessage());
    }
}`

The cache will now be handled by Redis, if the server is down, it will use the Files option
