### ISSUE TITLE
Cache Clean Problem?

### ISSUE THREAD

**Issue by jbcubed3** [PHPSocialNetwork/phpfastcache#274] opened 2016-05-01 11:11 UTC
Hi,

Having a problem with the clearing the cache and reading cache stats.

Code looks like this:
require_once("/phpfastcache/phpfastcache.php");
$cache = phpFastCache();
$cache->clean();

I can remove an individual cache object just fine with $cache->delete(); but clean();
is failing for some reason. Caching does seem to work though, just can't seem to clean() anymore - despite it working previously.

$array = $cache->stats();
print_r($array);

This outputs:
Array ( [info] => Array ( [Total [bytes]] => 0 [Expired and removed [bytes]] => 0 [Current [bytes]] => 0 ) [size] => 0 [data] => Array ( ) )

Any ideas on how to resolve? Am really stuck on this one!

**Comment by Geolim4** [comment] 2016-05-01 12:43
Hi,

What kind of driver are you using ?

Regards,

**Comment by jbcubed3** [comment] 2016-05-01 12:45
@Geolim4 - I'm using xampp on localhost at the moment, and phpfastcache set to auto

It's been working fine so far but today $cache->clean(); fails for some reason and not sure why!

**Comment by Geolim4** [comment] 2016-05-01 12:47
Can you debug your cache instance and tell me the kind of driver you are using ?

**Comment by jbcubed3** [comment] 2016-05-01 13:20
@Geolim4 - unfortunately not sure how for both questions, can you please elaborate

**Comment by khoaofgod** [comment] 2016-05-01 21:29
@jbcubed3 can you try this with latest version and see if the problem still there.

**Comment by jbcubed3** [comment] 2016-05-01 21:40
@khoaofgod - Hi - is there any other way to clear the cache?
I'm using this on localhost/XAMPP at the moment. I tried to use latest version, but getting some errors. 

$cache->delete, $cache->get and $cache->set work perfectly, just that $cache->clean just doesn't clear the cache out anymore - but I haven't changed any settings.

How do I debug the cache instance?

**Comment by khoaofgod** [comment] 2016-05-01 21:54
I will commit a new example file by tonight and let you know for u can run that test file for clean();

**Comment by Geolim4** [comment] 2016-05-02 06:07
Use var_dump() or get_class() and tell us the driver used.

**Comment by jbcubed3** [comment] 2016-05-02 08:21
Hi @Geolim4 - this is what I get for var_dump():

object(phpfastcache_files)#1 (4) { ["tmp"]=> array(0) { } ["config"]=> array(9) { ["storage"]=> string(4) "auto" ["default_chmod"]=> int(511) ["htaccess"]=> bool(true) ["path"]=> string(0) "" ["securityKey"]=> string(4) "auto" ["memcache"]=> array(1) { [0]=> array(3) { [0]=> string(9) "127.0.0.1" [1]=> int(11211) [2]=> int(1) } } ["redis"]=> array(5) { ["host"]=> string(9) "127.0.0.1" ["port"]=> string(0) "" ["password"]=> string(0) "" ["database"]=> string(0) "" ["timeout"]=> string(0) "" } ["extensions"]=> array(0) { } ["fallback"]=> string(5) "files" } ["fallback"]=> bool(false) ["instant"]=> NULL }

@khoaofgod amazing thank you

**Comment by jbcubed3** [comment] 2016-05-04 18:26
Hi @Geolim4 @khoaofgod - do you have any suggestions? Does the var_dump look okay?

**Comment by jbcubed3** [comment] 2016-05-12 21:04
Hi guys - any ideas?

**Comment by Geolim4** [comment] 2016-05-12 21:10
Does the target directory is writeable ?

**Comment by jbcubed3** [comment] 2016-05-12 21:11
Hi @Geolim4 - should be - I can read/write to the cache and create new objects - but I just can't clear it all for some reason!

**Comment by Geolim4** [comment] 2016-05-12 21:15
Weird, i can't reproduce it right now,i guess that you use Windows Env ?

**Comment by jbcubed3** [comment] 2016-05-12 21:15
Yep - using XAMPP for development/testing atm

**Comment by Geolim4** [comment] 2016-05-12 21:23
Do you have the possibility to test it on Lamp or even Map please (Linx/Mac) ?

**Comment by Geolim4** [comment] 2016-06-24 19:04
Fixed with #294 :)
We identified the bug in an other way.

**Closed by Geolim4** 2016-06-24 19:04 UTC
