### ISSUE TITLE
Missing cache items until page reload.

### ISSUE THREAD

**Issue by Yurciu** [PHPSocialNetwork/phpfastcache#511] opened 2017-09-06 11:26 UTC
### Configuration:

PhpFastCache version: 6.0.4
PHP version: 5.6.31
Operating system: Windows 10

#### Issue description:

I'm using Server-Sent Events, to print messages for user.

In infinite loop, every 10 seconds I check if there is any new item in cache to broadcast:

    $messages_to_broadcast = $this->_cache->getItemsByTag('inbox_message');
    foreach ($messages_to_broadcast as $key => $_message) {
        $_message = $_message->get();
        if($_message->recipient == $this->_user_id || $_message->recipient == 0){
            if(!is_null($html = \CRM\Engine\MessagingService::getMessageToBroadcast($_message))){
               echo "event: $_message->type \n";
               echo "data:{\n";
               echo "data:\"message_html\": \"$html\" \n";
               echo "data:}\n\n";
               $this->send_keepalive = false;
               $this->_cache->deleteItem($key);
           }
        }
    }

At irregular intervals, there is event, which save message to cache:

    $_cache_this = self::$_cache->getItem("message_".$_message->id);
    if(is_null($_cache_this->get())){
        $_cache_this->set($_message)
            ->expiresAfter(600)
            ->addTag('inbox_message');
        self::$_cache->save($_cache_this);
    }

The problem is that while I check in infinite loop for new items in cache, I get empty array. When I reload page, or browser reconnect to Server Side Events stream, item appears in cache. Is there any `flush` method I'm missing here?
I'm using `files` as cache method.

    \phpFastCache\CacheManager::setDefaultConfig(array(
        "path" => DIR_TMP
    ));
    global $cache;
    $cache = \phpFastCache\CacheManager::getInstance('files');

**Comment by Geolim4** [comment] 2017-09-06 21:17
Hello,

First:
Don't use `if(is_null($_cache_this->get())){` but `if($_cache_this->isHit()){`

Secondly, did you tried with another driver ? Like Redis or Memcache ?
Try it and tell me the result.
If a memory driver-based works, you are maybe dealing with a cache slam issue.
See https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV6%CB%96%5D-Dealing-with-cache-slams

Try it and tell me the results.

// Off topic
Please use json_[de|en]code for any json manipulation, it's really dirty to print your json response like that :(

Cheers,
Georges.L

**Comment by Yurciu** [comment] 2017-09-07 09:05
Hello,
Thank you for your quick reply.

I switch to Redis, and result is that same. Message is in Redis cache:
![image](https://user-images.githubusercontent.com/3920304/30153878-615eb668-93b8-11e7-970d-42c8fdd87bee.png)

So, should be visible after while, and broadcast:
![image](https://user-images.githubusercontent.com/3920304/30154054-f3af26ce-93b8-11e7-9629-f6a5e688df20.png)

But, if I refresh SSE stream, data is recived:
![image](https://user-images.githubusercontent.com/3920304/30154209-759f10fe-93b9-11e7-841a-6eeabb5bc18d.png)

I tried Your suggestion with cache slam either, with that same result.


// Off topic
Thx for your advice, I will fix code in refactor iteration. ;)

**Comment by Geolim4** [comment] 2017-09-07 18:24
`if(!is_null($html = \CRM\Engine\MessagingService::getMessageToBroadcast($_message))){`

Are you sure that you are trying to pass $_message as an object and not by the item cache key instead ?

**Comment by Yurciu** [comment] 2017-09-08 07:51
Yup, I'm sure:
```
$messages_to_broadcast = $this->_cache->getItemsByTag('inbox_message');
foreach ($messages_to_broadcast as $key => $_message) {
  var_Dump($_message); #phpFastCache\Drivers\Files\Item
  $_message = $_message->get();
  var_Dump($_message); #CRM\Message\SimpleNotification
  if($_message->recipient == $this->_user_id || $_message->recipient == 0){
    if(!is_null($html = \CRM\Engine\MessagingService::getMessageToBroadcast($_message))){
     //Broadcast code
     }
   }
}
```
![image](https://user-images.githubusercontent.com/3920304/30201471-337becb6-947b-11e7-8359-df8e50b147d9.png)

**Comment by Geolim4** [comment] 2017-09-08 17:52
To be honest I don't know if the bug is lib-related or your code-related.
Item Tags are deeply tested here:
https://github.com/PHPSocialNetwork/phpfastcache/blob/final/tests/ItemTags.test.php#L1

And the latest build is a success.
Are you sure that you don't have any concurrent job/call that delete/purge the items ?

Cheers,
Georges

**Comment by Yurciu** [comment] 2017-09-11 08:28
I will investigate further, but at this point I have impression that problematic is infinite loop or PHP language itself. I will isolate my code for you, for tests, if you want so.

I will switch implementation from Server Side Events to WebSockets, that will probably fix problem. When I do so, I'll let you know.

**Comment by Geolim4** [comment] 2017-09-11 17:59
Are you using a NTS/multi-threaded php installation ??

**Comment by Yurciu** [comment] 2017-09-12 10:03
![image](https://user-images.githubusercontent.com/3920304/30320223-5bd5ab9a-97b2-11e7-8c2f-79527d5f4784.png)

**Comment by Geolim4** [comment] 2017-09-12 22:11
Thanks for the heads up, but after some tests on tags I'm really unable to reproduce that :(
And you are the first one reporting me this kind of issue.

Let me know if you can reproduce it with a short code sample.

Cheers,
Georges

**Comment by Geolim4** [comment] 2017-09-16 11:31
As I'm publishing a new release today, I'm going to close this issue.

Feel free to reopen it if you have a working sample of code that I can reproduce :)

Cheers,
Georges

**Closed by Geolim4** 2017-09-16 11:31 UTC
Labels: 6.0, :] Not a bug, [-_-] In Process
