### ISSUE TITLE
Make cache to never expire ... not working ?

### ISSUE THREAD

**Issue by lambasoft** [PHPSocialNetwork/phpfastcache#343] opened 2016-08-08 20:56 UTC
Hey, I don't know what's wrong with my code, but for some reason my cache is getting removed in like 15 minutes even tho I have set the expiration time to 0.

This is my code:

    require 'vendor/autoload.php';
    use phpFastCache\CacheManager;
    use phpFastCache\Core\phpFastCache;
    if(!isset($InstanceCache)) {
        CacheManager::setDefaultConfig(array("path"=>"cache"));
        $InstanceCache = CacheManager::getInstance('sqlite');
    }
    $cache = $InstanceCache;
    $url = "http://www.website.com/api/call";
    $cache_key = md5($url);
    $CachedString = $cache->getItem($cache_key);
    $result = $CachedString->get();

    if (is_null($result)){
        // do the curl and get $result
        $result = sendRequest($url);
        // save the cache:
        $result = json_decode($result);
        // The setter, for those who missed it, put 0 meant cache it forever
        $CachedString->set($cache_key,$result, 0);
        // Save the cache item just like you do with doctrine and entities
        $InstanceCache->save($CachedString);
        echo "Cached {$url}:{$cache_key}";
    }else{
        $expires = $CachedString->getExpirationDate()->format(Datetime::W3C);
        echo "Already Cached: {$expires}:{$url}:{$cache_key}";
    }

Still it's getting an expiration date:
http://i.imgur.com/HrswK3i.png

What have you done wrong ? Thanks

**Comment by Geolim4** [comment] 2016-08-08 21:02
Ok got it

**Comment by Geolim4** [comment] 2016-08-08 21:05
Hello @lambasoft ,
This is the intended behavior, the default Ttl is based on 15 min (900 sec):
https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV5%5D-The-driver-options

Replace:

`$CachedString->set($cache_key,$result, 0);`

By:

`$CachedString->set($cache_key,$result)->expireAfter($seconds);`
Or
`$CachedString->set($cache_key,$result)->expireAt($dateTime);`

Or you can increase the default static config:
`CacheManager::setDefaultConfig(["path"=>"cache", "defaultTtl" => 86400]); // or more`


Cheers,
Georges

**Comment by lambasoft** [comment] 2016-08-08 21:05
So if I want it to never expire:
`$CachedString->set($cache_key,$result)->expireAfter(0);` ?

Thanks for the quick reply

**Comment by Geolim4** [comment] 2016-08-08 21:08
It depends the driver, but the 0 value can lead to some confusion, i recommend you to define a long date such a year or something like this.

**Comment by lambasoft** [comment] 2016-08-08 21:08
Thanks a lot, that's what I'll do ^.^

**Comment by Geolim4** [comment] 2016-08-08 21:09
Also remember the fact that a cache is NOT a database and should not be used as such :)

**Comment by Geolim4** [comment] 2016-08-08 21:09
Happy Poké-coding btw :D

**Comment by lambasoft** [comment] 2016-08-08 22:56
Sorry for bothering again, I didn't want to open a new issue.

I'm kind of new to the cache world, and have some questions I'd like to make clear.
You said that I should not use cache as a database, can you explain a bit further ?

I'm using phpfastcache to store information obtained from www.pokeapi.co, I'm fetching 151 pokemon from http://pokeapi.co/api/v2/pokemon/x ( where x is the pokemon id, from 1 to 151 ) and saving the page result as a cache using the code I showed above. Then every time a user browse my website, instead of doing 151 requests again, I simply use the cache to load the 151 pokemon with their detailed.

Does Cache fits this scenario ? Should I use files or sqlite ? 

Thanks a lot @Geolim4

**Comment by khoaofgod** [comment] 2016-08-08 23:00
@lambasoft it's fine to use it as a database in your situation, because you don't really care if you lose the data inside the cache, you can always fetch it from API again.
Just make it expire after 10 years LOL.

**Comment by lambasoft** [comment] 2016-08-08 23:04
Well, there's a problem, that if I'm looping through the 151 pokemon, for a reason it stops on the 71th value.

_This is an example code_
```
for($i=1;$i<=151;$i++){
    $CachedString = $cache->getItem($cache_key_$i);
    $result = $CachedString->get();
}
```

It seems I can't loop through more than 71 consecutive caches ?

**Comment by lambasoft** [comment] 2016-08-08 23:08
For further explanation this is my code:

        function sendRequest($url){
            //return $uri;
            $ch = curl_init();

            $timeout = 5;

            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
            $data = curl_exec($ch);

            $http_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);

            curl_close($ch);

            if ($http_code != 200) {
                return false;
            }

            return $data;
        }



        function getPokeAPI($url,$InstanceCache){
            $cache = $InstanceCache;

            $cache_key = md5($url);
            // $c->setCache($cache_key);
            $CachedString = $cache->getItem($cache_key);
            $result = $CachedString->get();

            if (is_null($result)){
                // do the curl and get $result
                $result = sendRequest($url);
                // save the cache:
                $result = json_decode($result);
                // The setter, for those who missed it, put 0 meant cache it forever
                $CachedString->set($result)->expiresAfter(31557600);
                 // Save the cache item just like you do with doctrine and entities
                $InstanceCache->save($CachedString);
                echo "Cached {$url}:{$cache_key}";
            }else{
                $expires = $CachedString->getExpirationDate()->format(Datetime::W3C);
                echo "Already Cached: {$expires}:{$url}:{$cache_key}";
            }

            echo "\r\n";
            return $result;
        }

        function test(){
            for($i=1;$i<=100;$i++){
                $result = getPokeAPI("http://pokeapi.co/api/v2/pokemon/{$i}/",$InstanceCache);
                $result = json_decode(json_encode($result), true);
                echo $result['name'] . " " . $i;
            }    
        }


When I run the function test() it stops on the 71th pokemon, but if I set $i=70 instead of $i=1 it shows the rest normally, so I'm sure cache files are not corrupted.

**Comment by khoaofgod** [comment] 2016-08-08 23:27
Check the PHP Timeout and the time, if it 30 second, try to make it more than that.
on php.ini

**Comment by khoaofgod** [comment] 2016-08-08 23:29
Also, debug at ur sendRequest($url); , to see if it stuck at that line or not, that mean you couldn't send request to the API and it stopped there when the 71 is none-cache.

**Comment by lambasoft** [comment] 2016-08-08 23:33
I did debug, and the 72th value is getting stuck on `$CachedString = $cache->getItem($cache_key);` the loops stops there on the 72th value.

PHP timeout has nothing to do, as everything loads within seconds and stops on 71th.

**Comment by lambasoft** [comment] 2016-08-09 00:03
I got an error:
`<b>Fatal error</b>:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 286387 bytes)`

Why did phpcache used my rams memory ? I should restart my pc ?

**Comment by lambasoft** [comment] 2016-08-09 00:21
Alright! I fixed it!

I had to add  `$cache->detachAllItems();` to the end of my getPokeAPI() function, so I release the memory from my RAMS.

I think this should be added to the wiki or examples.

Thanks a lot for your time @khoaofgod , we may close this now.

**Comment by Geolim4** [comment] 2016-08-09 06:35
Mhhhh weird how much data do you store per item?

Le 9 août 2016 2:21 AM, "Ayman Abi Aoun" <notifications@github.com> a
écrit :

Alright! I fixed it!

I had to add $cache->detachAllItems(); to the end of my getPokeAPI()
function, so I release the memory from my RAMS.

I think this should be added to the wiki or examples.

Thanks a lot for your time @khoaofgod <https://github.com/khoaofgod> , we
may close this now.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/PHPSocialNetwork/phpfastcache/issues/343#issuecomment-238417556>,
or mute the thread

**Comment by Geolim4** [comment] 2016-08-09 11:15
150 Cache Item is not that much unless if you store more than 500Ko per item, in that case you can quickly reach the max allowed memory.

**Comment by hammermaps** [comment] 2016-08-09 11:26
Is APC or Memchache/Couchbase Server not better for this Projekt?

Or save your API Data to NoSQL -> MongodB?

**Comment by Geolim4** [comment] 2016-08-09 14:02
Absolutely, high-performance driver must be used for this kind of application. (see readme.md)

**Closed** 2016-08-11 11:12 UTC
Labels: 0_0 question, Not a bug :]
