### ISSUE TITLE
getStats() (DriverStatistic) is very slow (and size is not correct) on files adapter

### ISSUE THREAD

**Issue by stamster** [PHPSocialNetwork/phpfastcache#766] opened 2020-10-27 10:19 UTC
**Configuration (optional)**
- **PhpFastCache version:** 8.0.2
- **PhpFastCache API version:** 3.0.0
- **PHP version:** PHP 7.4.11 
- **Operating system:** GNU/Linux (Ubuntu 18.04.5 LTS)

**My question**

I have two concerns here.

This is the actual output of `getStats()` method:

```php
Phpfastcache\Entities\DriverStatistic Object
(
    [info:protected] => Number of files used to build the cache: 25336
    [size:protected] => 4955612
    [data:protected] => 
    [rawData:protected] => Array
        (
            [tmp] => Array
                (
                    [95febb24d3424412e9afa40e20547d1a] => /var/xyz/cache/domain.com/Files
                )

        )

)
```

1. Size - this should represent size in bytes? While in reality `/var/xyz/cache/domain.com/Files` has a total size of 183 MB
2. Performance - it takes 12 secs to load this page with stats. I'm aware files are slow (disk is not SSD), so it might be logical for 183MB of small files it takes that much to calculate, but size reported by OS / file system and getStats method are not even close?

Am I doing something wrong here?

**Comment by Geolim4** [comment] 2020-10-27 15:39
Hello,

I'm investigating, but I don't get that size difference, would you mind to send me a ZIP of this directory `/var/xyz/cache/domain.com/Files` on my email if this is not too sensitive ?

contact(-at-)geolim4.com

I might have an idea, but I'm not really sure.
Cheers,
Georges

**Comment by stamster** [comment] 2020-10-27 17:25
Hi Georges,

thanks for involvement here. 

I have sent you an email with tar.gz attached (1.2 MB compressed).

I hope it won't be in your spam/junk folder.


Thanks

Stam

**Comment by Geolim4** [comment] 2020-10-28 00:56
Hello,

I finally made some tests and I'm unable to reproduce this bug, as you can see in the screenshoot below:
![image](https://user-images.githubusercontent.com/1332071/97377526-29d7f500-18b8-11eb-82a2-77b95f9e655f.png)

The size in the zip and on the disk are **exactly** the same oO.

If you can dig deeper on your side and bring me more information and perhaps a patch, I'm in :)

Cheers,
Georges

**Comment by Geolim4** [comment] 2020-10-28 01:00
Just by curiosity open the file:
lib/Phpfastcache/Core/Pool/IO/IOHelperTrait.php

Search for:
`        $path = $this->getFilePath(false);`
And add below:
`clearstatcache();`

Tell me if this solve your issue.

**Comment by stamster** [comment] 2020-10-28 08:51
Hi Georges,

thanks for getting your hands on this. I appropriate it. 


```diff
+++ b/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Core/Pool/IO/IOHelperTrait.php
@@ -52,6 +52,7 @@ trait IOHelperTrait
     {
         $stat = new DriverStatistic();
         $path = $this->getFilePath(false);
+        clearstatcache(); //debug - Geolim4
 
         if (!is_dir($path)) {
             throw new PhpfastcacheIOException("Can't read PATH:" . $path);
```

That didn't help.

If I delete all the files by hand - getStats() is fast and shows 0 bytes and only 1 file (autogenerated .htaccess file I assume). And as the number of files grow - the performance hit increases gradually. 

Also on your example you're running Windows. Perhaps it's related to GNU/Linux only (bug).


I'll try to dig deeper to see where exactly is the bottleneck (with Timer) and I'll post here. 

To be continued... :)

**Comment by Geolim4** [comment] 2020-10-28 18:27
The time spend is definitely caused by number of files, but I can't really do something about it, except maybe adding a bash command which could be blocked in some installation due to the call to shell_exec :(

**Comment by stamster** [comment] 2020-10-29 15:19
![image](https://user-images.githubusercontent.com/12804479/97593747-43855380-1a02-11eb-9f43-2d72619fdf8a.png)

Well well - here's the culprit. 

Total runtime is indeed 26 secs now. So both method calls take 13 secs to execute.


My use case is 25k of items, each item being very small (4 bytes, e.g. score), so lots of files especially I see lots of directories dispersed by Php Fast Cache.

**Comment by stamster** [comment] 2020-10-29 15:39
```bash 
find Files/ -type f | wc -l

25375
```

Yep. 

The odd thing is that I've moved cache dir into shared RAM page `/run/shm`, but still I see apache2 taking 100% CPU during this 25+ secs runtime when I call the stats on page. So the bottleneck here is recursive iterator and not disk I/O.

E.g.

```php
  $objects = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path), RecursiveIteratorIterator::SELF_FIRST);
        foreach ($objects as $object) {
....

```

**Comment by stamster** [comment] 2020-10-29 15:42
I will try to sort this out and perhaps send PR.
OR I can organize my cache into one large array with 25k items - so key will be always the same `my_cache` and then I'll search needle in a haystack there on array, it should be faster and stats would work just fine then apparently.

**Comment by Geolim4** [comment] 2020-10-29 20:07
This is the problem with high programming level, no matter the implementation you cannot really deal easily when manipulating lot of files :(

**Comment by Geolim4** [comment] 2020-10-29 23:42
However your use case tells me that you may have to think about switching to more efficient cache backend, redis maybe ?

**Comment by stamster** [comment] 2020-10-30 07:38
This was v1 of the cache solution :) So it works superb for normal use - e.g. app asks cache store whenever the item is not expired and returns it with simple `get()` method call.
Where it hits performance is only on `getStats()` method call. And that's not used by anyone by me with special access param :) 

Indeed memcached would be next thing - but this just works for now. 

I'll try to test though with one big associative array to see if that is of any help and to measure the performance. Will be interesting.

**Comment by Geolim4** [comment] 2020-10-30 20:56
Maybe you should cache your cache stats.
Ohh wait :P

**Comment by Geolim4** [comment] 2020-10-30 21:00
More seriously you can override the Files driver to extends the getStats() methods and replace them by a shell_exec implementation :)

**Comment by Geolim4** [comment] 2020-11-03 17:20
If you have implemented such implementation, feel free to post it here, I'm closing this one for now, but you can always ask me to reopen it ;)

**Closed** 2020-11-03 17:21 UTC
Labels: 0_0 Bug, 7.1, 8.0, :) Temporary closed

**Comment by stamster** [comment] 2020-11-04 07:34
Sure, thanks Geolim4.

The core of the problem remains - why calculated total size is plain wrong? 

I'll try to debug this and post results.
